// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int greater = 0;
		int less = 0;
		double rnd;
		double ratio;

		for (int i = 0; i < times; i ++){
			rnd = Math.random();
			if (rnd > 0.5){
				greater ++;
			}

			else{
				less ++;
			}
		}
		
		if (less == 0){
			ratio = 0;
		}

		else{
			ratio = Double.valueOf(greater)/Double.valueOf(less);
		}

		System.out.println("> 0.5: " + greater + " times\n <= 0.5: " + less + " times\n Ratio: " + ratio);
		
	}
}
